// <auto-generated />
using System;
using CoreIdentity.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreIdentity.Persistence.Migrations
{
    [DbContext(typeof(CoreIdentityDbContext))]
    [Migration("20240210025950_include-company")]
    partial class includecompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.1.1-servicing")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Claims", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 2, 10, 10, 59, 49, 798, DateTimeKind.Local).AddTicks(3362),
                            RoleName = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 2, 10, 10, 59, 49, 798, DateTimeKind.Local).AddTicks(3365),
                            RoleName = "Operator"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 2, 10, 10, 59, 49, 798, DateTimeKind.Local).AddTicks(3367),
                            RoleName = "Master Agent"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 2, 10, 10, 59, 49, 798, DateTimeKind.Local).AddTicks(3368),
                            RoleName = "Agent"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 2, 10, 10, 59, 49, 798, DateTimeKind.Local).AddTicks(3369),
                            RoleName = "Player"
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId")
                        .IsUnique()
                        .HasFilter("[AdminUserId] IS NOT NULL");

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantAudience", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AudienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId", "AudienceId");

                    b.HasIndex("AudienceId");

                    b.ToTable("TenantAudience", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantKey", b =>
                {
                    b.Property<Guid>("TenantKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantKeyId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantKey", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantUser", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<bool>("ChangePassword")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNumber"));

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("MobilePrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    // b.HasData(
                    //     new
                    //     {
                    //         Id = new Guid("153351ca-456d-4c8d-870d-1c9aca0a112a"),
                    //         Attempts = 0,
                    //         ChangePassword = false,
                    //         CreatedOn = new DateTime(2024, 2, 10, 10, 59, 49, 800, DateTimeKind.Local).AddTicks(8314),
                    //         Email = "juanTmadAdmin@gmail.com",
                    //         EmailConfirmed = true,
                    //         IdNumber = 0,
                    //         Locked = false,
                    //         MobileNumber = "09090909099",
                    //         MobilePrimary = true,
                    //         Password = "NPbsoJTFnoLOut2PrQpeMZNGui/YwUwVn2JrLPCuRIuXG/CFsejj6X+hi2TvUmnH3NqJ33Z4xcD/CXAJuinWhQ==",
                    //         PasswordSalt = "2JhQiT08xCW7sXczjHh2tEdJJa4DkyAUVuqgTnACbKg=",
                    //         UserName = "juanTmadAdmin"
                    //     },
                    //     new
                    //     {
                    //         Id = new Guid("517257b7-a537-4107-95c0-905f04e49c67"),
                    //         Attempts = 0,
                    //         ChangePassword = false,
                    //         CreatedOn = new DateTime(2024, 2, 10, 10, 59, 49, 850, DateTimeKind.Local).AddTicks(7391),
                    //         Email = "juanTmadOperator@gmail.com",
                    //         EmailConfirmed = true,
                    //         IdNumber = 0,
                    //         Locked = false,
                    //         MobileNumber = "09090909099",
                    //         MobilePrimary = true,
                    //         Password = "vqH+Ua8Zq5mJepZhInX+YCEhxtY6CWTwR8MeOnTCmtuP1FVDl9dWFNZjPqvRM9I5fHHJTctwSRfC7c/ARqq//w==",
                    //         PasswordSalt = "Fyfa2E2VSsJ0Kzy3ds6g0DH3SSzeqCSN1BbdHd8f200=",
                    //         UserName = "juanTmadOperator"
                    //     },
                    //     new
                    //     {
                    //         Id = new Guid("9c47d44e-7c53-4ded-b52f-3478c178ce43"),
                    //         Attempts = 0,
                    //         ChangePassword = false,
                    //         CreatedOn = new DateTime(2024, 2, 10, 10, 59, 49, 904, DateTimeKind.Local).AddTicks(6900),
                    //         Email = "juanTmadMasterAgent@gmail.com",
                    //         EmailConfirmed = true,
                    //         IdNumber = 0,
                    //         Locked = false,
                    //         MobileNumber = "09090909099",
                    //         MobilePrimary = true,
                    //         Password = "ZUlV8XqJ35AlAcQuU9ADsz+i7BQSo/QFDRsElkqFtWFczJZ61PMK4VFLKje6/o3WSW9xWbWEaU0nxxqdx0lIrQ==",
                    //         PasswordSalt = "NPnxGqLBQQeQ95y3Mne1+ZZhOfB65Dr2WM5p99r7Bgg=",
                    //         UserName = "juanTmadMasterAgent"
                    //     },
                    //     new
                    //     {
                    //         Id = new Guid("34256ae5-de73-426c-8748-de0e9c608377"),
                    //         Attempts = 0,
                    //         ChangePassword = false,
                    //         CreatedOn = new DateTime(2024, 2, 10, 10, 59, 49, 956, DateTimeKind.Local).AddTicks(7190),
                    //         Email = "juanTmadAgent@gmail.com",
                    //         EmailConfirmed = true,
                    //         IdNumber = 0,
                    //         Locked = false,
                    //         MobileNumber = "09090909099",
                    //         MobilePrimary = true,
                    //         Password = "qx204OmXcumePgFgAnOaKS/dc6m3dmjcKW3ibobVFwmzZ03nr6LP0c6JTm0xE6mPSFuLQOCMM5At9Mgykfoqog==",
                    //         PasswordSalt = "6EvZ8Hf2GompfqpAceul3xJkDbYS9Rqm/qx+aiLGqws=",
                    //         UserName = "juanTmadAgent"
                    //     },
                    //     new
                    //     {
                    //         Id = new Guid("87d079fb-4d7b-4be5-9739-78b16dd07c81"),
                    //         Attempts = 0,
                    //         ChangePassword = false,
                    //         CreatedOn = new DateTime(2024, 2, 10, 10, 59, 50, 8, DateTimeKind.Local).AddTicks(9501),
                    //         Email = "juanTmadPlayer@gmail.com",
                    //         EmailConfirmed = true,
                    //         IdNumber = 0,
                    //         Locked = false,
                    //         MobileNumber = "09090909099",
                    //         MobilePrimary = true,
                    //         Password = "DkdbEh00tyU/jGY+6HMISVtGvZl35pp4J9sPXxn1nLQ6Gdqorz4oGGAT+u03lRxzKOm4nHXbw+F2iLhVXN67tQ==",
                    //         PasswordSalt = "5hJhm4Vp08iT/kO0QATirRoiqxAOLvFzO7OsXiMqgJo=",
                    //         UserName = "juanTmadPlayer"
                    //     });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserClaims", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserKey", b =>
                {
                    b.Property<int>("UserKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserKeyId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserKeyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserKey", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserLog", b =>
                {
                    b.Property<int>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLogId"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("LoginDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserLogId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLog", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    // b.HasData(
                    //     new
                    //     {
                    //         UserId = new Guid("153351ca-456d-4c8d-870d-1c9aca0a112a"),
                    //         RoleId = 1
                    //     },
                    //     new
                    //     {
                    //         UserId = new Guid("517257b7-a537-4107-95c0-905f04e49c67"),
                    //         RoleId = 2
                    //     },
                    //     new
                    //     {
                    //         UserId = new Guid("9c47d44e-7c53-4ded-b52f-3478c178ce43"),
                    //         RoleId = 3
                    //     },
                    //     new
                    //     {
                    //         UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                    //         RoleId = 4
                    //     },
                    //     new
                    //     {
                    //         UserId = new Guid("87d079fb-4d7b-4be5-9739-78b16dd07c81"),
                    //         RoleId = 5
                    //     });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "AdminUser")
                        .WithOne("TenantAdmin")
                        .HasForeignKey("CoreIdentity.Domain.Entity.Tenant", "AdminUserId");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantAudience", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Audience")
                        .WithMany("TenantAudiences")
                        .HasForeignKey("AudienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audience");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantKey", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("TenantKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantUser", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserClaims", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Claims", "Claims")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claims");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserKey", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserLog", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("UserLogs")
                        .HasForeignKey("TenantId");

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserRoles", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Roles", "Roles")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Claims", b =>
                {
                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Roles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.Navigation("TenantAudiences");

                    b.Navigation("TenantKeys");

                    b.Navigation("TenantUsers");

                    b.Navigation("UserLogs");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.User", b =>
                {
                    b.Navigation("TenantAdmin")
                        .IsRequired();

                    b.Navigation("TenantUsers");

                    b.Navigation("UserClaims");

                    b.Navigation("UserKeys");

                    b.Navigation("UserLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
