// <auto-generated />
using System;
using CoreIdentity.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreIdentity.Persistence.Migrations
{
    [DbContext(typeof(CoreIdentityDbContext))]
    [Migration("20240204050932_updateLogin")]
    partial class updateLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.1.1-servicing")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Claims", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 653, DateTimeKind.Local).AddTicks(4656),
                            RoleName = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 653, DateTimeKind.Local).AddTicks(4773),
                            RoleName = "Operator"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 653, DateTimeKind.Local).AddTicks(4778),
                            RoleName = "Master Agent"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 653, DateTimeKind.Local).AddTicks(4782),
                            RoleName = "Agent"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 653, DateTimeKind.Local).AddTicks(4785),
                            RoleName = "Player"
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId")
                        .IsUnique()
                        .HasFilter("[AdminUserId] IS NOT NULL");

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantAudience", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AudienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId", "AudienceId");

                    b.HasIndex("AudienceId");

                    b.ToTable("TenantAudience", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantKey", b =>
                {
                    b.Property<Guid>("TenantKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantKeyId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantKey", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantUser", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<bool>("ChangePassword")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNumber"));

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("MobilePrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ddd94ac-51d8-4688-a3aa-23aab22c1554"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 663, DateTimeKind.Local).AddTicks(4284),
                            Email = "juanTmadAdmin@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "m7zDkbTPXA0rOnWN9uPFQHKXqtQmmoIlz4JdeH3BjNQ2YoR6ceNA5wU4tfVr68//PYwnUM8mpO2XDt2ino55yg==",
                            PasswordSalt = "xP83ledzy4vsg2Nk1mfs4ghY5xJ33BM4FgY8Z8CBjCE=",
                            UserName = "juanTmadAdmin"
                        },
                        new
                        {
                            Id = new Guid("78cf1a61-a484-43b9-9e07-8f6503dedee0"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 748, DateTimeKind.Local).AddTicks(2925),
                            Email = "juanTmadOperator@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "kpFwbcc8x1s3i6Zco0JjFU8jWeto87S0BSHZbtJQjZQzgXdb/ndb80kXtQpzj0Zmsd1vRAz03ysYMh+tjtXp+A==",
                            PasswordSalt = "2fCWLeBV4y8l/i4xYVOKISlJABn+q1G3pFdQY8LuHko=",
                            UserName = "juanTmadOperator"
                        },
                        new
                        {
                            Id = new Guid("ad1cac91-f172-4fbb-9f5c-dd22b5c78740"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 830, DateTimeKind.Local).AddTicks(6077),
                            Email = "juanTmadMasterAgent@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "IFh0LaQu7NdasqH4zIjE7u+1jURcTiz+IX8rdjYRIi+ixrDyc+/a7czxuphALxJx2Ce8C1i4UNJZY03q9x24Pg==",
                            PasswordSalt = "Q7iiC9/nXaZ/YiLI2eRRTzNKAmjTUEXN7qRmHxtQhtc=",
                            UserName = "juanTmadMasterAgent"
                        },
                        new
                        {
                            Id = new Guid("e2922d48-78b7-46a9-9e4c-7138850faa8e"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 903, DateTimeKind.Local).AddTicks(5643),
                            Email = "juanTmadAgent@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "gFzbdXtQCou92N9Qz5LoGdmI6ooBValig5GIhdWgGLE1V2yAhGj8fCWAbOWqXph6z7vaDR72cU5X5+PhvfxxwA==",
                            PasswordSalt = "IhLx4TC7tfEEDjHDAPPLxX7/WV/BPktruZFwpC9aEm4=",
                            UserName = "juanTmadAgent"
                        },
                        new
                        {
                            Id = new Guid("501f564b-8cff-49d9-bb1e-3e654139b989"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 2, 4, 13, 9, 31, 971, DateTimeKind.Local).AddTicks(6764),
                            Email = "juanTmadPlayer@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "gCzxmRoiMP4OBQlmzqpOEnw7SkUxUOd/3hkFN9krZewDUXqbcD6YTDRHoBEajL6C7YrzA/R3Yi2s9DA6wPsTdg==",
                            PasswordSalt = "vzRjR+o5cqN84+qMkoq/X6vkVOF5Z8iSZPZPpfPvUrE=",
                            UserName = "juanTmadPlayer"
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserClaims", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserKey", b =>
                {
                    b.Property<int>("UserKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserKeyId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserKeyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserKey", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserLog", b =>
                {
                    b.Property<int>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLogId"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("LoginDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserLogId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLog", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("3ddd94ac-51d8-4688-a3aa-23aab22c1554"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("78cf1a61-a484-43b9-9e07-8f6503dedee0"),
                            RoleId = 2
                        },
                        new
                        {
                            UserId = new Guid("ad1cac91-f172-4fbb-9f5c-dd22b5c78740"),
                            RoleId = 3
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            RoleId = 4
                        },
                        new
                        {
                            UserId = new Guid("501f564b-8cff-49d9-bb1e-3e654139b989"),
                            RoleId = 5
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "AdminUser")
                        .WithOne("TenantAdmin")
                        .HasForeignKey("CoreIdentity.Domain.Entity.Tenant", "AdminUserId");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantAudience", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Audience")
                        .WithMany("TenantAudiences")
                        .HasForeignKey("AudienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audience");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantKey", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("TenantKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantUser", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserClaims", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Claims", "Claims")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claims");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserKey", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserLog", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("UserLogs")
                        .HasForeignKey("TenantId");

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserRoles", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Roles", "Roles")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Claims", b =>
                {
                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Roles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.Navigation("TenantAudiences");

                    b.Navigation("TenantKeys");

                    b.Navigation("TenantUsers");

                    b.Navigation("UserLogs");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.User", b =>
                {
                    b.Navigation("TenantAdmin")
                        .IsRequired();

                    b.Navigation("TenantUsers");

                    b.Navigation("UserClaims");

                    b.Navigation("UserKeys");

                    b.Navigation("UserLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
