// <auto-generated />
using System;
using CoreIdentity.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreIdentity.Persistence.Migrations
{
    [DbContext(typeof(CoreIdentityDbContext))]
    [Migration("20240324152050_AdjustStringLength")]
    partial class AdjustStringLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "1.1.1-servicing")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Claims", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Claims", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 49, 843, DateTimeKind.Local).AddTicks(629),
                            RoleName = "Super Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 49, 843, DateTimeKind.Local).AddTicks(632),
                            RoleName = "Operator"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 49, 843, DateTimeKind.Local).AddTicks(634),
                            RoleName = "Master Agent"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 49, 843, DateTimeKind.Local).AddTicks(635),
                            RoleName = "Agent"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 49, 843, DateTimeKind.Local).AddTicks(636),
                            RoleName = "Player"
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId")
                        .IsUnique()
                        .HasFilter("[AdminUserId] IS NOT NULL");

                    b.ToTable("Tenant", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantAudience", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AudienceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.HasKey("TenantId", "AudienceId");

                    b.HasIndex("AudienceId");

                    b.ToTable("TenantAudience", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantKey", b =>
                {
                    b.Property<Guid>("TenantKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantKeyId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantKey", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantUser", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<bool>("ChangePassword")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IdNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNumber"));

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Locked")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("MobilePrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cba2ada5-6aac-4cb8-9575-83609f28dec3"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 49, 845, DateTimeKind.Local).AddTicks(8977),
                            Email = "juanTmadAdmin@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "Q5jRr6ZfVu0VRDnThfUo2NKSp3fd3kefYO72LcSn78+YXV+GC1Q0NXoMiSbQYC2iyf0eQpX0HfBS2gSUJUoFTw==",
                            PasswordSalt = "C82toLJZT+ehVGz01R9sHXvnGLcgPE9xCzq3ZqAOBPc=",
                            UserName = "juanTmadAdmin"
                        },
                        new
                        {
                            Id = new Guid("fd0473d0-782a-4759-8eba-87e55bbf8746"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 49, 897, DateTimeKind.Local).AddTicks(6037),
                            Email = "juanTmadOperator@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "dUy8YKDVqdJSsEVOrgEB09AcPTcbmDIOvLTbyKgtrE9aJa8ZIupsDJiDYdl4pbaOLlOROM0UyxIvDKGW1BNIiw==",
                            PasswordSalt = "Vq2Jm0vyQ2YrQn3IP8iCKq6OT2cNpZj/7SOq0ixiOmE=",
                            UserName = "juanTmadOperator"
                        },
                        new
                        {
                            Id = new Guid("09df74ba-ee71-4e5f-90a4-7c1e51297716"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 49, 950, DateTimeKind.Local).AddTicks(3900),
                            Email = "juanTmadMasterAgent@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "mWaVCfJnQQMX1EESeMftcjKuob/puxmg6fxhvtFlGuW5U3EJYiFTaf9+LDfmj/mrA9GDf78tKkOvayaOYgEosQ==",
                            PasswordSalt = "hm0mt1KSHEpzYv7KEhj24ufgQqOgohJjYgR4xuBa564=",
                            UserName = "juanTmadMasterAgent"
                        },
                        new
                        {
                            Id = new Guid("c96c7370-43fe-4626-b327-cc4f7dd3c995"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 50, 14, DateTimeKind.Local).AddTicks(2087),
                            Email = "juanTmadAgent@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "hqnNe9XRhyMQ9DezLHkqjbPnJpvBaCOfJdiAJhYxyXNjLYQAZBnSl2stA9QZKd9BiRMOQrWL3IIcLRdYGacFFQ==",
                            PasswordSalt = "MCm34P6r1FHan5Skf6FVo1JHcTkHH0WZOthU1SlqKn8=",
                            UserName = "juanTmadAgent"
                        },
                        new
                        {
                            Id = new Guid("68b4b3dd-0786-42d3-a6f4-20bab79b1869"),
                            Attempts = 0,
                            ChangePassword = false,
                            CreatedOn = new DateTime(2024, 3, 24, 23, 20, 50, 78, DateTimeKind.Local).AddTicks(9767),
                            Email = "juanTmadPlayer@gmail.com",
                            EmailConfirmed = true,
                            IdNumber = 0,
                            Locked = false,
                            MobileNumber = "09090909099",
                            MobilePrimary = true,
                            Password = "UOGLz0HEkAluMRLtj283TT1XfL17WnwvfqbZ1biWrvrTOJhp97jJ/Vk7SYRcr2ED5UA3WlWwFBH/IJr+svXKjQ==",
                            PasswordSalt = "ZsBlveWv/bVIG+Lqc5hwjkU5qys6+Du1nROgYmUVAws=",
                            UserName = "juanTmadPlayer"
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserClaims", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "ClaimId");

                    b.HasIndex("ClaimId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserDeviceToken", b =>
                {
                    b.Property<Guid>("UserDeviceTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserDeviceTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserDeviceToken", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserKey", b =>
                {
                    b.Property<int>("UserKeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserKeyId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserKeyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserKey", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserLog", b =>
                {
                    b.Property<int>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLogId"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("LoginDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserLogId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLog", (string)null);
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserRoles", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("cba2ada5-6aac-4cb8-9575-83609f28dec3"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("fd0473d0-782a-4759-8eba-87e55bbf8746"),
                            RoleId = 2
                        },
                        new
                        {
                            UserId = new Guid("09df74ba-ee71-4e5f-90a4-7c1e51297716"),
                            RoleId = 3
                        },
                        new
                        {
                            UserId = new Guid("00000000-0000-0000-0000-000000000000"),
                            RoleId = 4
                        },
                        new
                        {
                            UserId = new Guid("68b4b3dd-0786-42d3-a6f4-20bab79b1869"),
                            RoleId = 5
                        });
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "AdminUser")
                        .WithOne("TenantAdmin")
                        .HasForeignKey("CoreIdentity.Domain.Entity.Tenant", "AdminUserId");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantAudience", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Audience")
                        .WithMany("TenantAudiences")
                        .HasForeignKey("AudienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audience");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantKey", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("TenantKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.TenantUser", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserClaims", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Claims", "Claims")
                        .WithMany("UserClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claims");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserDeviceToken", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserDeviceTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserKey", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserLog", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Tenant", "Tenant")
                        .WithMany("UserLogs")
                        .HasForeignKey("TenantId");

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.UserRoles", b =>
                {
                    b.HasOne("CoreIdentity.Domain.Entity.Roles", "Roles")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreIdentity.Domain.Entity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Claims", b =>
                {
                    b.Navigation("UserClaims");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Roles", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.Tenant", b =>
                {
                    b.Navigation("TenantAudiences");

                    b.Navigation("TenantKeys");

                    b.Navigation("TenantUsers");

                    b.Navigation("UserLogs");
                });

            modelBuilder.Entity("CoreIdentity.Domain.Entity.User", b =>
                {
                    b.Navigation("TenantAdmin")
                        .IsRequired();

                    b.Navigation("TenantUsers");

                    b.Navigation("UserClaims");

                    b.Navigation("UserDeviceTokens");

                    b.Navigation("UserKeys");

                    b.Navigation("UserLogs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
